// If you already have your settings.gradle, please insert this configuration to the appropriate places.

include "common"
project (":common").projectDir = file("common")

include "FigafIRTinfrastructure"
project (":FigafIRTinfrastructure").projectDir = file("FigafIRTinfrastructure")

include "com.sap.integration.dsi"
project (":com.sap.integration.dsi").projectDir = file("com.sap.integration.dsi")

include "FigafJiraIntegration"
project (":FigafJiraIntegration").projectDir = file("FigafJiraIntegration")

include "NewPackage"
project (":NewPackage").projectDir = file("NewPackage")

include "FigafIRTinfrastructure:iflow-LatencyTest"
project (":FigafIRTinfrastructure:iflow-LatencyTest").projectDir = file("FigafIRTinfrastructure/IntegrationFlow/LatencyTest")

include "com.sap.integration.dsi:sc-com.sap.integration.dsi.dataplane.scripts"
project (":com.sap.integration.dsi:sc-com.sap.integration.dsi.dataplane.scripts").projectDir = file("com.sap.integration.dsi/ScriptCollection/com.sap.integration.dsi.dataplane.scripts")

include "FigafIRTinfrastructure:iflow-Figaf_HTTP_to_JMS"
project (":FigafIRTinfrastructure:iflow-Figaf_HTTP_to_JMS").projectDir = file("FigafIRTinfrastructure/IntegrationFlow/Figaf_HTTP_to_JMS")

include "com.sap.integration.dsi:iflow-com.sap.integration.dsi.dataplane.copy"
project (":com.sap.integration.dsi:iflow-com.sap.integration.dsi.dataplane.copy").projectDir = file("com.sap.integration.dsi/IntegrationFlow/com.sap.integration.dsi.dataplane.copy")

include "NewPackage:iflow-Test_Flow_Two"
project (":NewPackage:iflow-Test_Flow_Two").projectDir = file("NewPackage/IntegrationFlow/Test_Flow_Two")

include "FigafIRTinfrastructure:iflow-IRTHTTPtoProcessDirect"
project (":FigafIRTinfrastructure:iflow-IRTHTTPtoProcessDirect").projectDir = file("FigafIRTinfrastructure/IntegrationFlow/IRTHTTPtoProcessDirect")

include "FigafJiraIntegration:iflow-Update_Jira_Issues"
project (":FigafJiraIntegration:iflow-Update_Jira_Issues").projectDir = file("FigafJiraIntegration/IntegrationFlow/Update_Jira_Issues")

include "FigafJiraIntegration:iflow-Update_Figaf_Transport_from_Jira"
project (":FigafJiraIntegration:iflow-Update_Figaf_Transport_from_Jira").projectDir = file("FigafJiraIntegration/IntegrationFlow/Update_Figaf_Transport_from_Jira")

include "NewPackage:iflow-Test_Flow"
project (":NewPackage:iflow-Test_Flow").projectDir = file("NewPackage/IntegrationFlow/Test_Flow")

include "FigafJiraIntegration:iflow-Search_Jira_Issues"
project (":FigafJiraIntegration:iflow-Search_Jira_Issues").projectDir = file("FigafJiraIntegration/IntegrationFlow/Search_Jira_Issues")

include "FigafIRTinfrastructure:sc-FigafMigration"
project (":FigafIRTinfrastructure:sc-FigafMigration").projectDir = file("FigafIRTinfrastructure/ScriptCollection/FigafMigration")

include "FigafJiraIntegration:mm-Message_Mapping_one"
project (":FigafJiraIntegration:mm-Message_Mapping_one").projectDir = file("FigafJiraIntegration/MessageMapping/Message_Mapping_one")

include "FigafJiraIntegration:sc-T_Script_Col"
project (":FigafJiraIntegration:sc-T_Script_Col").projectDir = file("FigafJiraIntegration/ScriptCollection/T_Script_Col")

include "com.sap.integration.dsi:iflow-com.sap.integration.dsi.dataplane.generic"
project (":com.sap.integration.dsi:iflow-com.sap.integration.dsi.dataplane.generic").projectDir = file("com.sap.integration.dsi/IntegrationFlow/com.sap.integration.dsi.dataplane.generic")

